project_id = "pdjoltmgwmsoekbvbwjh"
[functions.group_users]
enabled = true
verify_jwt = true
import_map = "./functions/group_users/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/group_users/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/group_users/*.html" ]
