export const Database = {
    public: {
      Tables: {
        applications: {
          Row: {
            applicant_id: "",
            cover_letter: null,
            created_at: null,
            id: "",
            job_id: "",
            resume_url: null,
            status: null,
            updated_at: null,
          },
          Insert: {
            applicant_id: "",
            cover_letter: null,
            created_at: null,
            id: "",
            job_id: "",
            resume_url: null,
            status: null,
            updated_at: null,
          },
          Update: {
            applicant_id: "",
            cover_letter: null,
            created_at: null,
            id: "",
            job_id: "",
            resume_url: null,
            status: null,
            updated_at: null,
          },
          Relationships: [
            {
              foreignKeyName: "applications_job_id_fkey",
              columns: ["job_id"],
              isOneToOne: false,
              referencedRelation: "jobs",
              referencedColumns: ["id"],
            },
          ],
        },
        jobs: {
          Row: {
            company: "",
            created_at: null,
            description: "",
            id: "",
            is_active: null,
            job_type: "",
            location: null,
            posted_by: "",
            requirements: null,
            salary_range: null,
            title: "",
            updated_at: null,
          },
          Insert: {
            company: "",
            created_at: null,
            description: "",
            id: "",
            is_active: null,
            job_type: "",
            location: null,
            posted_by: "",
            requirements: null,
            salary_range: null,
            title: "",
            updated_at: null,
          },
          Update: {
            company: "",
            created_at: null,
            description: "",
            id: "",
            is_active: null,
            job_type: "",
            location: null,
            posted_by: "",
            requirements: null,
            salary_range: null,
            title: "",
            updated_at: null,
          },
          Relationships: [],
        },
        profiles: {
          Row: {
            avatar_url: null,
            bio: null,
            created_at: null,
            first_name: null,
            id: "",
            is_recruiter: null,
            last_name: null,
            location: null,
            phone: null,
            title: null,
            updated_at: null,
          },
          Insert: {
            avatar_url: null,
            bio: null,
            created_at: null,
            first_name: null,
            id: "",
            is_recruiter: null,
            last_name: null,
            location: null,
            phone: null,
            title: null,
            updated_at: null,
          },
          Update: {
            avatar_url: null,
            bio: null,
            created_at: null,
            first_name: null,
            id: "",
            is_recruiter: null,
            last_name: null,
            location: null,
            phone: null,
            title: null,
            updated_at: null,
          },
          Relationships: [],
        },
        saved_jobs: {
          Row: {
            created_at: null,
            id: "",
            job_id: "",
            user_id: "",
          },
          Insert: {
            created_at: null,
            id: "",
            job_id: "",
            user_id: "",
          },
          Update: {
            created_at: null,
            id: "",
            job_id: "",
            user_id: "",
          },
          Relationships: [
            {
              foreignKeyName: "saved_jobs_job_id_fkey",
              columns: ["job_id"],
              isOneToOne: false,
              referencedRelation: "jobs",
              referencedColumns: ["id"],
            },
          ],
        },
      },
      Views: {},
      Functions: {},
      Enums: {},
      CompositeTypes: {},
    },
  };
  